# Generated by Django 2.2.10 on 2021-11-22 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_auto_20210926_1434'),
        ('stock', '0006_auto_20211120_1058'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.FloatField(default=0.0)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('total_price', models.FloatField(default=0.0)),
                ('sub_total_price', models.FloatField(default=0.0)),
                ('discount_persentage', models.FloatField(default=0.0)),
                ('issued_date', models.DateTimeField(auto_now=True, null=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Issued'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('quote_pdf', models.FileField(blank=True, null=True, upload_to='core/static/assets/documents/quotations/')),
                ('description', models.TextField(blank=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
                ('product_ids', models.ManyToManyField(blank=True, null=True, to='quotation.QProduct')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='qproduct',
            name='quote_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotation.Quotation'),
        ),
    ]
