# Generated by Django 2.2.10 on 2022-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='product_ids',
            field=models.ManyToManyField(blank=True, to='quotation.QProduct'),
        ),
    ]
