# Generated by Django 2.2.10 on 2021-11-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0015_auto_20211119_1752'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material_ids',
            field=models.ManyToManyField(blank=True, null=True, to='purchase_order.CMaterial'),
        ),
    ]
