# Generated by Django 2.2.10 on 2021-11-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20211119_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'In Stock'), (1, 'Out Stock')], default=1),
        ),
    ]
