# Generated by Django 2.2.10 on 2021-11-20 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20211119_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_material',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Product'),
        ),
    ]
