# Generated by Django 2.2.10 on 2022-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20211120_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customers_id',
            field=models.ManyToManyField(blank=True, to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_ids',
            field=models.ManyToManyField(blank=True, to='stock.Product_Material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quatity',
            field=models.FloatField(default=0.0),
        ),
    ]
