# Generated by Django 2.2.10 on 2022-01-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20220108_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_material',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
