# Generated by Django 2.2.10 on 2021-10-20 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0002_auto_20210926_1435'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0007_auto_20211019_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quatity', models.IntegerField(default=0)),
                ('material_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.Materials')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('total_price', models.FloatField(default=0.0)),
                ('sub_total_price', models.FloatField(default=0.0)),
                ('issued_date', models.DateTimeField(auto_now=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('Received_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Issued'), (1, 'Paid'), (2, 'Received'), (2, 'Closed')], default=0)),
                ('po_pdf', models.FileField(null=True, upload_to='core/static/assets/documents/purchase order/')),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Supplier')),
                ('material_ids', models.ManyToManyField(blank=True, null=True, to='purchase_order.CMaterial')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
