# Generated by Django 2.2.10 on 2021-10-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='customer_id',
            new_name='supplier_id',
        ),
    ]
