# Generated by Django 2.2.10 on 2021-10-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_auto_20211020_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_persentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
