# Generated by Django 2.2.10 on 2021-10-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_auto_20211020_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmaterial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cmaterial',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_pdf',
            field=models.FileField(blank=True, null=True, upload_to='core/static/assets/documents/purchase order/'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'Issued'), (1, 'Paid'), (2, 'Received'), (3, 'Closed')], default=0),
        ),
    ]
