# Generated by Django 2.2.10 on 2021-11-01 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_auto_20211030_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmaterial',
            name='po_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_order.PurchaseOrder'),
        ),
    ]
