# Generated by Django 2.2.10 on 2021-11-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_auto_20211019_1229'),
        ('purchase_order', '0007_remove_cmaterial_material_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmaterial',
            name='material_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.Materials'),
        ),
    ]
