# Generated by Django 2.2.10 on 2021-11-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0008_cmaterial_material_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmaterial',
            name='description',
            field=models.TextField(blank=True, default=' PO Description', null=True),
        ),
    ]
