# Generated by Django 2.2.10 on 2021-11-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0009_auto_20211101_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmaterial',
            name='description',
        ),
    ]
