# Generated by Django 2.2.10 on 2021-11-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0010_remove_cmaterial_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmaterial',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
