# Generated by Django 2.2.10 on 2021-11-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0011_auto_20211101_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmaterial',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
