# Generated by Django 2.2.10 on 2021-11-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0012_auto_20211102_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmaterial',
            name='po_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase_order.PurchaseOrder'),
        ),
    ]
