# Generated by Django 2.2.10 on 2021-11-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0013_auto_20211102_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmaterial',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
