# Generated by Django 2.2.10 on 2022-01-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0016_auto_20220108_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmaterial',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
