# Generated by Django 2.2.10 on 2021-09-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='orders_count',
            field=models.IntegerField(default=0),
        ),
    ]
