# Generated by Django 2.2.10 on 2021-09-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210917_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
