# Generated by Django 2.2.10 on 2021-09-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210917_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_img',
            field=models.ImageField(default='core/static/assets/images/customer/default.png', null=True, upload_to='core/static/assets/images/customer'),
        ),
    ]
