# Generated by Django 2.2.10 on 2021-09-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0002_auto_20210926_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Shell',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('row', models.IntegerField(max_length=12)),
                ('column', models.IntegerField(max_length=12)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('shell_state', models.IntegerField(choices=[(0, 'Empty'), (1, 'Partialy Filled'), (2, 'Filled')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('unit_price', models.FloatField()),
                ('quatity', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=0)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.Categories')),
                ('shell_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.Shell')),
                ('supplier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.Supplier')),
            ],
        ),
    ]
