# Generated by Django 2.2.10 on 2021-10-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20211003_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='stock_margin',
            field=models.IntegerField(default=0),
        ),
    ]
