# Generated by Django 2.2.10 on 2021-10-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_materials_stock_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='shell',
            name='description',
            field=models.CharField(default='', max_length=350),
        ),
    ]
