# Generated by Django 2.2.10 on 2021-10-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_shell_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shell',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
