# Generated by Django 2.2.10 on 2021-10-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20211019_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shell',
            old_name='shell_state',
            new_name='status',
        ),
    ]
