# Generated by Django 2.2.10 on 2021-11-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20211102_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Stock'), (0, 'Out Stock')], default=0),
        ),
    ]
