# Generated by Django 2.2.10 on 2021-11-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_auto_20211126_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='status',
            field=models.IntegerField(choices=[(0, 'Out Stock'), (1, 'In Stock')], default=1),
        ),
    ]
