# Generated by Django 2.2.10 on 2022-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_auto_20211211_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='quatity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shell',
            name='column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shell',
            name='row',
            field=models.IntegerField(),
        ),
    ]
