# Generated by Django 2.2.10 on 2021-09-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_baseuser_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='user/default.png', null=True, upload_to='user'),
        ),
    ]
