# Generated by Django 2.2.10 on 2021-09-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_baseuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='static/assets/images/user/default.png', null=True, upload_to='static/assets/images/user'),
        ),
    ]
