# Generated by Django 2.2.10 on 2021-09-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210908_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='core/static/assets/images/user/default.png', null=True, upload_to='core/static/assets/images/user'),
        ),
    ]
