# Generated by Django 2.2.10 on 2021-09-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210909_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='mobile_number',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
