# Generated by Django 2.2.10 on 2021-09-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210913_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='mobile_number',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
