# Generated by Django 2.2.10 on 2022-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20210913_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='mobile_number',
            field=models.IntegerField(blank=True),
        ),
    ]
