# Generated by Django 2.2.10 on 2022-02-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20220108_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
