# Generated by Django 2.2.10 on 2021-11-15 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('customer', '0004_auto_20210926_1434'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.FloatField(default=0.0)),
                ('material_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('total_price', models.FloatField(default=0.0)),
                ('sub_total_price', models.FloatField(default=0.0)),
                ('discount_persentage', models.FloatField(default=0.0)),
                ('tax_rate', models.FloatField(default=0.0)),
                ('issued_date', models.DateTimeField(auto_now=True, null=True)),
                ('Produced_date', models.DateTimeField(blank=True, null=True)),
                ('Sended_date', models.DateTimeField(blank=True, null=True)),
                ('Returned_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Issued'), (1, 'Producing'), (2, 'Sended'), (3, 'Returned'), (4, 'Closed')], default=0)),
                ('so_pdf', models.FileField(blank=True, null=True, upload_to='core/static/assets/documents/purchase order/')),
                ('description', models.TextField(blank=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Customer')),
                ('product_ids', models.ManyToManyField(blank=True, null=True, to='sales_order.CProduct')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cproduct',
            name='po_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_order.SalesOrder'),
        ),
    ]
