# Generated by Django 2.2.10 on 2021-11-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0002_auto_20211115_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cproduct',
            old_name='material_id',
            new_name='product_id',
        ),
    ]
