# Generated by Django 2.2.10 on 2021-11-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order', '0003_auto_20211115_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='so_pdf',
            field=models.FileField(blank=True, null=True, upload_to='core/static/assets/documents/sales order/'),
        ),
    ]
