# Generated by Django 2.2.10 on 2021-09-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_img',
            field=models.ImageField(default='core/static/assets/images/supplier/default.png', null=True, upload_to='core/static/assets/images/supplier'),
        ),
    ]
