# Generated by Django 2.2.10 on 2022-05-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20220108_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='fax_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
