# Generated by Django 2.2.10 on 2021-11-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'From Sales Order'), (2, 'From Pre Sales Order')], default=0),
        ),
    ]
