# Generated by Django 2.2.10 on 2022-01-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20220108_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'From Sales Order'), (2, 'From Pre Sales Order')], default=1),
        ),
    ]
