# Generated by Django 2.2.10 on 2022-04-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_product',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
    ]
