# Generated by Django 2.2.10 on 2021-11-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_sales_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pproduct',
            old_name='so_id',
            new_name='pso_id',
        ),
        migrations.RenameField(
            model_name='presalesorder',
            old_name='so_pdf',
            new_name='pso_pdf',
        ),
    ]
