# Generated by Django 2.2.10 on 2022-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_sales_order', '0002_auto_20211120_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presalesorder',
            name='product_ids',
            field=models.ManyToManyField(blank=True, to='pre_sales_order.PProduct'),
        ),
    ]
